export const StraightHairData = () => [
  {
    id: 1,
    name: "straight-1",
    price: 200,
    inStock: true,
    image: "straight-1",
    cartNumber: 0,
  },
  {
    id: 2,
    name: "straight-2",
    price: 200,
    inStock: true,
    image: "straight-2",
    cartNumber: 0,
  },
  {
    id: 3,
    name: "straight-3",
    price: 200,
    inStock: true,
    image: "straight-3",
    cartNumber: 0,
  },
  {
    id: 4,
    name: "straight-4",
    price: 200,
    inStock: true,
    image: "straight-4",
    cartNumber: 0,
  },
  {
    id: 5,
    name: "straight-5",
    price: 200,
    inStock: true,
    image: "straight-5",
    cartNumber: 0,
  },
  {
    id: 6,
    name: "straight-6",
    price: 200,
    inStock: true,
    image: "straight-6",
    cartNumber: 0,
  },
  {
    id: 7,
    name: "straight-7",
    price: 200,
    inStock: true,
    image: "straight-7",
    cartNumber: 0,
  },
  {
    id: 8,
    name: "straight-8",
    price: 200,
    inStock: true,
    image: "straight-8",
    cartNumber: 0,
  },
  {
    id: 9,
    name: "straight-9",
    price: 200,
    inStock: true,
    image: "straight-9",
    cartNumber: 0,
  },
  {
    id: 10,
    name: "straight-10",
    price: 200,
    inStock: true,
    image: "straight-10",
    cartNumber: 0,
  },
  {
    id: 11,
    name: "straight-11",
    price: 200,
    inStock: true,
    image: "straight-11",
    cartNumber: 0,
  },
  {
    id: 12,
    name: "straight-12",
    price: 200,
    inStock: true,
    image: "straight-12",
    cartNumber: 0,
  },
  {
    id: 13,
    name: "straight-13",
    price: 200,
    inStock: true,
    image: "straight-13",
    cartNumber: 0,
  },
  {
    id: 14,
    name: "straight-14",
    price: 200,
    inStock: true,
    image: "straight-14",
    cartNumber: 0,
  },
  {
    id: 15,
    name: "straight-15",
    price: 200,
    inStock: true,
    image: "straight-15",
    cartNumber: 0,
  },
  {
    id: 16,
    name: "straight-16",
    price: 200,
    inStock: true,
    image: "straight-16",
    cartNumber: 0,
  },
];

export const FavoriteHair = () => [
  {
    id: 101,
    name: "Blue Straight",
    price: 350,
    inStock: true,
    image: "straight-1",
    cartNumber: 0,
  },
  {
    id: 102,
    name: "Wavy Blonde",
    price: 210,
    inStock: true,
    image: "wavy-2",
    cartNumber: 0,
  },
  {
    id: 103,
    name: "Black Curly",
    price: 225,
    inStock: true,
    image: "curly-4",
    cartNumber: 0,
  },
  {
    id: 104,
    name: "Bouncy Hair",
    price: 315,
    inStock: true,
    image: "bouncy-4",
    cartNumber: 0,
  },
];

export const BouncyHair = () => [
  {
    id: "b1",
    name: "Blonde Bouncy",
    price: 350,
    inStock: true,
    image: "bouncy-1",
    cartNumber: 0,
  },
  {
    id: "b2",
    name: "Black Bouncy",
    price: 210,
    inStock: true,
    image: "bouncy-2",
    cartNumber: 0,
  },
  {
    id: "b3",
    name: "Black Bouncy",
    price: 225,
    inStock: true,
    image: "bouncy-3",
    cartNumber: 0,
  },
  {
    id: "b4",
    name: "Bouncy Hair",
    price: 315,
    inStock: true,
    image: "bouncy-4",
    cartNumber: 0,
  },
  {
    id: "b5",
    name: "Black Bouncy",
    price: 225,
    inStock: true,
    image: "bouncy-5",
    cartNumber: 0,
  },
  {
    id: "b6",
    name: "Bouncy Hair",
    price: 315,
    inStock: true,
    image: "bouncy-6",
    cartNumber: 0,
  },
];
export const CurlyHair = () => [
  {
    id: "c1",
    name: "Curly Hair",
    price: 350,
    inStock: true,
    image: "curly-1",
    cartNumber: 0,
  },
  {
    id: "c2",
    name: "Black Curly",
    price: 210,
    inStock: true,
    image: "curly-2",
    cartNumber: 0,
  },
  {
    id: "c3",
    name: "Black Curly",
    price: 225,
    inStock: true,
    image: "curly-3",
    cartNumber: 0,
  },
  {
    id: "c4",
    name: "Curly Hair",
    price: 315,
    inStock: true,
    image: "curly-4",
    cartNumber: 0,
  },
  {
    id: "c5",
    name: "Black Curly",
    price: 225,
    inStock: true,
    image: "curly-5",
    cartNumber: 0,
  },
  {
    id: "c6",
    name: "Curly Hair",
    price: 315,
    inStock: true,
    image: "curly-6",
    cartNumber: 0,
  },
];
export const WavyHair = () => [
  {
    id: "w1",
    name: "Wavy Hair",
    price: 350,
    inStock: true,
    image: "wavy-1",
    cartNumber: 0,
  },
  {
    id: "w2",
    name: "Black Wavy",
    price: 210,
    inStock: true,
    image: "wavy-2",
    cartNumber: 0,
  },
  {
    id: "w3",
    name: "Black wavy",
    price: 225,
    inStock: true,
    image: "wavy-3",
    cartNumber: 0,
  },
  {
    id: "w4",
    name: "wavy Hair",
    price: 315,
    inStock: true,
    image: "wavy-4",
    cartNumber: 0,
  },
];
export const OurTeam = () => [
  {
    name: "Imelda Agubata",
    position: "CEO/Executive Director",
    image: "straight-18",
  },
  { name: "Sarah Williams", position: "General Manager", image: "bouncy-2" },
  { name: "Laureen Moore", position: "Sales Manager", image: "bouncy-4" },
];

export const cartItem = () => [];

export const NigerianStates = () => [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];
export const Budget = () => [
  "₦50,000 - ₦99,000",
  "₦100,000 - #299,000",
  "₦300,000 And Above",
];
export const HairType = () => [
  "Straight Hair",
  "Wavy Hair",
  "Curly Hair",
  "Bouncy Hair",
];
